spring:
  jackson:
    time-zone: GMT+8
  profiles:
    active: dev
  datasource:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/common_ms?&useSSL=false
      username: root
      password:

      initial-size: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

logging:
  level:
    priv.zzz: info
  config: classpath:logback-spring.xml
  file:
    path: ./logs

mybatis:
  type-aliases-package: com.priv.model
  # 配置注解+XML方式的扫描路径
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true

swagger:
  enable: true

